-- liquibase formatted sql

--changeSet Anatoly:1
CREATE TABLE transport(
    id                   bigint generated by default as identity primary key,
    mark                 text,
    model                text,
    category             text,
    gos_number           text unique,
    types                text,
    year_release         int,
    availability_trailer BOOLEAN DEFAULT 'no');

--changeSet Anatoly:2
INSERT INTO transport(mark, model, category, gos_number, types, year_release)
VALUES ('audi', 'a4', 'A', 'a111aa58', 'PASSENGER', 2012);
INSERT INTO transport(mark, model, category, gos_number, types, year_release, availability_trailer)
VALUES ('vw', 'golf 7', 'B', 'b222bb58', 'PASSENGER', 2022, '0');
INSERT INTO transport(mark, model, category, gos_number, types, year_release, availability_trailer)
VALUES ('lada', 'vesta', 'C', 'c333cc58', 'PASSENGER', 2020, '1');